#name=input('Enter your full name :')
#result=len(name)
#result=name.find('')
#result=name.rfind('o')
#name=name.capitalize()
#name=name.upper()
#name=name.lower()
#result=name.isdigit()
#result=name.isalpha()
#phone_number=input('Enter the phone number')
#result=phone_number.count('-')
#print(result)
print(help(str))